### ISSUE TITLE
obsolete doc?

### ISSUE THREAD

**Issue by c-cube** [vincent-hugot/iTeML#16]
[online documentation][http://batteries.vhugot.com/qtest/qtest001.html#htoc7) doesn't seem to detail all the combinators for quick-checks (as seen [here][https://github.com/vincent-hugot/iTeML/blob/master/qtest/quickcheck.mli)). For instance `fun1` or `option` are missing.

Side note: many combinators from @gasche 's [library](https://github.com/gasche/random-generator) would be useful (especially monadic or applicative constructs).

**Comment by vincent-hugot** [comment]
Mostly fixed by #19 .
