### ISSUE TITLE
quickcheck library unclear or missing

### ISSUE THREAD

**Issue by mwweissmann** [vincent-hugot/iTeML#22]
using the example from the README.md, I need the quickcheck module mentioned in the "Q" style tests. Which library is this exactly or is it included in qtest somewhere?
It would be nice to at least document this in the README.md.

**Comment by vincent-hugot** [comment]
It is installed along with qtest, eg. by the opam package.

What is your output when running testfoo.sh in qtest/tests/ ?

**Comment by mwweissmann** [comment]
I suppose the problem is one of case-sensitivity:
The package is actually named 'QTest2Lib' while README.md refers to it as 'qtest2lib'; I guess that this works just fine on case-insensitive file systems but fails on case-sensitive ones.
I did not see it in the output of ```ocamlfind```as uppercase packages are listed first -- and QTest2Lib is the only library not restricting it's name to lowercase characters.

**Comment by vincent-hugot** [comment]
Ha, the name changed at some point, I believe.

I'll correct the occurrences in the readme. Thanks for pointing this out.

**Comment by mwweissmann** [comment]
thanks!
