### ISSUE TITLE
Unbound module QCheck

### ISSUE THREAD

**Issue by dannywillems** [vincent-hugot/iTeML#34]
Hello

I installed qtest with opam
```Shell
opam install qtest
```
Next, I created a foo.ml file containing
```OCaml
(*$T f
 f 2 3 = 5
*)
let f a b = a + b
```
The test file generation is ok with
```Shell
qtest -o foo_test.ml extract foo.ml
```
But when I try to build
```
ocamlbuild -cflags -warn-error,+26 -use-ocamlfind -package oUnit foo_test.native
```
I have
Error: Unbound module QCheck
```
What did I do wrong ?

**Comment by c-cube** [comment]
try adding `-package qcheck` in the compilation flags. It contains `QCheck` and `QCheck_runners` which are required for the generated code.

**Comment by dannywillems** [comment]
Thanks, it's working.
