### ISSUE TITLE
Count is ignored, test stops on first failure

### ISSUE THREAD

**Issue by copy** [vincent-hugot/iTeML#38]
In the following example, I'd expect that 10000000 examples are generated and then the smallest one (0) is printed, however it seems to stop after the first test:

``` ocaml
(*$Q & ~count:10000000
  (Q.make ~print:string_of_int ~small:(fun i -> i) (fun s -> Random.int 1000)) (fun i -> i = i + 1)
*)
```

Maybe I'm misunderstanding the documentation?

**Comment by c-cube** [comment]
Indeed, that seems to be a bug. I have to confess I mostly use shrinking (which is really awesome) but sometimes it's too complicated to write. I will look into it!

**Comment by c-cube** [comment]
After a more thorough look, the current situation with `max_fail`, `max_gen`, `small` and `shrink` is a bit too complicated. I think we should force a choice between shrinking and generating a number of cases within `[count, max_gen]` (and maybe keep the smallest one(s) if `small` is provided).

**Comment by c-cube** [comment]
Please re-open if you think there still is a bug! With the latest release it should only print "0".
