### ISSUE TITLE
output faulty diagnostics in color

### ISSUE THREAD

**Issue by UnixJunkie** [vincent-hugot/iTeML#46]
Hello, it would be nice if the output final diagnostics are in color.
Especially the faulty ones, like in yellow or red.
So that I can eyeball quickly if anything went wrong.

**Comment by c-cube** [comment]
This should be in [qcheck](/c-cube/qcheck) instead, I think (in the test runner). Are you thinking of just the last 'success' or 'failure', or individual test results?

**Comment by c-cube** [comment]
@UnixJunkie you can try to pin qcheck and recompile your tests. Display of the final result will be in colors (unless `--no-colors` is specified).

**Comment by UnixJunkie** [comment]
it works. Thanks. I think the important part is that anything faulty should by default be displayed in color
(like yellow or red or orange).

**Comment by c-cube** [comment]
You mean each test's failure? That's a good remark indeed.

**Comment by c-cube** [comment]
Last commit puts more colors.

**Comment by c-cube** [comment]
(please close if it's good enough for you :-))

**Comment by UnixJunkie** [comment]
thanks a lot!
