### ISSUE TITLE
generated code lines longer than 80 chars

### ISSUE THREAD

**Issue by UnixJunkie** [vincent-hugot/iTeML#9]
That may be nice to have them shorter
so that people can eyeball them more comfortably
or even edit them if they need to.

**Comment by c-cube** [comment]
@UnixJunkie does it also happen with "raw" tests? Those with `(*$R` or `(*$QR`? If not, I will close the issues, as most tests should be one line anyway.

**Comment by UnixJunkie** [comment]
It's OK to close, thanks.
